launchdarkly-server-sdk-1.0-0.rockspec
**Requirements**
**Related issues**
None applicable.
**Describe the solution you've provided**
There is a bug in the 1.0.0 rockspec where it doesn't install version 1.0.0, rather it actually installs the latest version of the library from master. This caused a CI failure for us, since we pinned the version of the LD C API as well as the version of the LD Lua server SDK, but since the Lua server SDK was secretly rolling-release, things got out of sync due to an update here.
<details>
<summary>Before my change</summary>
```
Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /usr/bin/luarocks with sudo, you may want sudo's -H flag. …
```
=> Set tag for 1.0.0 rockspec

.github/actions/build-docs/action.yml, .github/actions/publish-docs/action.yml, .github/workflows/manual-publish-docs.yml, scripts/build-docs.sh
Adds missing `luaVersion` workflow parameter to manual-build-docs. Also ensures `ldoc` is install on the CI runner.
=> ci: fix docs publishing workflow

.github/actions/ci/action.yml, .gitignore, README.md, launchdarkly-server-sdk-1.0-0.rockspec, launchdarkly-server-sdk-redis-1.0-0.rockspec, launchdarkly-server-sdk-redis.c, launchdarkly-server-sdk.c, redis-test.lua, scripts/compile.sh, scripts/get-cpp-sdk-locally.sh, test-redis.lua, test.lua
This PR updates the Lua SDK to build against the C++ Server-side SDK with Redis v3.x via its provided C bindings. 
It will be the first `v2` release of this SDK.
The shape of the SDK mostly remains the same, with the major changes being:
- Users are replaced with contexts (`makeUser` is a wrapper, added`makeContext`)
- Configuration overhaul (nested configurations, type checking, data system)
- Removed obsolete config options and methods (like `alias`)
- Removed global logger config
=> feat!: use C++ Server-side SDK 3.0 bindings [v2]

.github/workflows/release-please.yml
Forgot to add the `lua-version` to our release-please workflow, so that failed when I merged a release PR. Luckily we don't actually release any packages, so the only thing that we've missed was updating docs.
=> ci: add latest lua version to release-please workflow

scripts/update-versions.sh
When testing the `update versions` action, I found that it fails when existing rockspec matches the existing version. 
This updates the script to gracefully quit instead.
=> ci: gracefully handle already up-to-date rockspec version

.github/workflows/release-please.yml
This adds a new step after release-please runs: updating the `.rockspec` file names / versions and README example. It targets the release PR.
This requires updating to `release-please@v4`, which meant some changes. To facilitate testing these, I've added the `workflow_dispatch` trigger to the workflow.
=> ci: release-please updates rockspec version

launchdarkly-server-sdk.c
**Requirements**
**Related issues**
**Describe the solution you've provided**
endpoint_fields are declared with the following fields: `pollingBaseURL`, `streamingBaseURL` and `eventsBaseURL`
```
struct field_validator endpoint_fields[] = {
FIELD("pollingBaseURL", LUA_TSTRING, parse_string, LDServerConfigBuilder_ServiceEndpoints_PollingBaseURL),
FIELD("streamingBaseURL", LUA_TSTRING, parse_string, LDServerConfigBuilder_ServiceEndpoints_StreamingBaseURL),
FIELD("eventsBaseURL", LUA_TSTRING, parse_string, LDServerConfigBuilder_ServiceEndpoints_EventsBaseURL)
};
```
The provided documentation doesn't match:
**Describe alternatives you've considered**
Fix function docs at: 
```
@tparam[opt] string config.serviceEndpoints.streamingBaseURL Set the streaming URL
for connecting to LaunchDarkly. …
```
=> docs: fix clientInit documentation

.github/actions/ci/action.yml, .github/workflows/manual-publish-docs.yml, .github/workflows/release-please.yml, README.md, launchdarkly-server-sdk-2.0.0-0.rockspec, launchdarkly-server-sdk-redis-2.0.0-0.rockspec, launchdarkly-server-sdk.c, release-please-config.json
This updates the existing `.rockspec`'s to match our currently released `2.0.0` version. 
Additionally, I've refactored the `ci` workflow to take the rockspec package names as inputs. Otherwise when the versions rev, our CI will break since it's currently hardcoded to `1.0`. 
docs: fix mis-named clientInit method
=> ci: update rockspec version to match released version

.github/actions/ci/action.yml, examples/hello-lua-server/hello.lua
This incorporates a hello-lua example directly into the repo, allowing us to archive [hello-lua-server](https://github.com/launchdarkly/hello-lua-server).
I'm labeling this as a fix because it should have been included in the first release - this shouldn't trigger a minor version, but it's still helpful to test the release process with a patch.
=> fix: add hello-lua-server example

.github/actions/update-versions/action.yml, .github/workflows/release-please.yml, README.md, launchdarkly-server-sdk-2.0.0-0.rockspec, launchdarkly-server-sdk-redis-2.0.0-0.rockspec, release-please-config.json, scripts/update-versions.sh
This hardcodes (using `x-release-please-version`) the proper version in `./scripts/version-updater.sh`.
This also uses `x-release-please-version` for the README and the internal version numbers of the `rockspec`'s - previously this wasn't the case because I thought it might not work.
I'm hoping it is smart enough to deal with the `-0` suffix in the line that it is updating.
=> ci: use release-please to hardcode the version in version-updater.sh

scripts/compile.sh
**Requirements**
**Related issues**
No related issues
**Describe the solution you've provided**
After updating tag to 2.0.1, rockspec was also updated, but the compile script was not.
**Describe alternatives you've considered**
Update compile script to read the new version of the rockspec.
**Additional context**
Found it after trying to compile it again with the new update version.
=> fix: after update tag to 2.0.1 rockspec was also updated

release-please-config.json, scripts/compile.sh
Adds `compile.sh` to `extra-files`. This script is used to compile both base+redis SDKs locally for convenience.
=> chore: update compile.sh with release-please

.github/workflows/release-please.yml
Step outputs are cast to strings. So `false` == `'false'`, and `true == 'true'`.
Right now the `'false'` is output from release-please's `prs_created`. And in an expression, that is evaluated as `true`. Because it's a non-empty string, I think?
Instead, compare against the actual string 'true'.
=> ci: use explicit comparison to string 'true' in release-please.yml

.github/workflows/release-please.yml
The `release-please` workflow is slightly complicated in that it has two phases - stuff to run when there's a release PR, and stuff to run if a release was actually created.
The `actions/checkout` only ran if `prs_created == 'true'`. 
This means that when the release PR was merged, it wouldn't run - and therefore the post-release steps couldn't succeed. This removes the guard so the repo is always checked out.
=> ci: always checkout code when running release-please workflow

.github/actions/ci/action.yml, .github/actions/publish/action.yml, .github/actions/rockspec-names/action.yml, .github/workflows/ci.yml, .github/workflows/manual-publish.yml, release-please-config.json
Adds a manual publishing workflow for LuaRocks. Once I've proved it actually works, we can add it to the `release-please` workflow. 
Note: this won't work until the AWS role variable is present in the repo configuration.
=> ci: add manual publish to LuaRocks

.github/workflows/manual-publish.yml
Filepath was wrong for the manual publish workflow's invocation of the `rockspec-names` action.
=> ci: fix action filepath in manual-publish workflow

.github/actions/publish/action.yml
Looks like luarocks upload has a dependency on having a `json` library installed. This adds a `luarocks install lua-cjson` call.
=> ci: install lua-cjson in publish step

.github/workflows/manual-publish.yml
The description of options in the manual publish step are a bit verbose. This shortens them and makes them easier to read.
=> ci: improve UX of manual publish step

launchdarkly-server-sdk-2.0.2-0.rockspec, launchdarkly-server-sdk-redis-2.0.2-0.rockspec
Now that we have a published luarocks module, we can have the redis rockspec depend on the base server.
=> chore(deps): make redis rockspec depend on base server SDK

.github/actions/install-cpp-sdk-redis/action.yml, .github/actions/rockspec-names/action.yml, .github/workflows/install-lua-sdk.yml, .github/workflows/manual-publish.yml
As a sanity check after publishing a LuaRock module, it'd be good to `luarocks install` it on a fresh runner to test that it actually worked.
=> ci: add installation test after publishing package

.github/workflows/install-lua-sdk.yml
The problem being solved here is that `workflow_dispatch`, `workflow_call`, and `schedule` events are often all useful for a single workflow. 
That is - you might want a workflow to run based on:
1. A UI interaction
2. Another workflow calling it
3. On a regular schedule
The first two, and perhaps the last, are all relevant for `install-lua-sdk`. We might have a one-off test for a particular Lua version, triggered in Github UI (1). 
We might run this after `release-please` publishes a package (2). 
And finally, we might want to ensure the package is installable every day (3).
To make this actually work, you need to ensure default values are assigned for each input. The cleanest way to do that seems to be some duplication and a "ternary" technique with environment variables.
Honestly this …
=> ci: update install-lua-sdk workflow with unified default values

.github/workflows/manual-publish.yml
The reusable workflow paths used `./github` instead of `./.github`.
=> ci: fix typo in manual-publish.yml

.github/workflows/manual-publish.yml
In [a previous PR](https://github.com/launchdarkly/lua-server-sdk/pull/65), I refactored the `rockspec-info` into a reusable workflow. 
As part of that work, I had added a `rockspec` parameter to the CI workflow. I neglected to update `manual-publish` which calls that workflow; this PR adds the parameter.
I've also simplified the publishing step. Instead of having a bunch if `if` guards that run steps depending on if you've specified `server`, `redis`, or `both`, it's just a matrix job where the matrix is defined by the workflow input. Looks slightly ugly in the UI, but does the job.
Additionally, I think the `install` step of the workflow isn't appropriate. The idea was to publish the package and then subsequently install it as a sanity check, but I think that could be quite flaky if …
=> ci: fix invocation of ci workflow from manual-publish

.github/workflows/manual-publish.yml, .github/workflows/release-please.yml
Updates `release-please` workflow to actually perform a release, in a similar manner to recently merged `manual-publish` workflow.
-------------------------
There's one main difference: in the manual workflow, it uses a matrix to publish both packages. Here, it publishes the server first, and the redis integration next.
I don't really know which technique will be better for this repo so I'm splitting the difference. 
Sequential avoids a race condition where Redis integration version X depends on server Y (but it's not yet published), and also has `fail-fast: true` so if the server doesn't publish, the redis integration won't publish. 
It's also more amenable to making this be a true multi-package repo in the future (right now both packages are always published for any releasable unit.) …
=> ci: publish packages with release-please

.github/workflows/ci.yml, README.md, examples/hello-haproxy/Dockerfile, examples/hello-haproxy/README.md, examples/hello-haproxy/haproxy.cfg, examples/hello-haproxy/service.lua
Incorporates the [`hello-haproxy`](https://github.com/launchdarkly/hello-haproxy) example directly into the repo so it can be continually tested and kept up-to-date.
This is `fix` because:
- Should have been in the repo in the first place :) 
- Test out `release-please`, but..
- ..doesn't generate a new minor version
=> fix: add hello-haproxy

.github/workflows/release-please.yml
This is purely for testing out release-please, and should be reverted.
=> ci: use release-please fork with error logging

.github/workflows/release-please.yml, .github/workflows/rockspec-info.yml, release-please-config.json, scripts/update-versions.sh
This should _actually_ fix release please!
The root cause of the errors seems to have been that you cannot update a Github workflow file using `extra-files` in a release please manifest. This is disallowed by the Github API. 
I've refactored the `rockspec-info` workflow to not need to be updated at all. Instead, it grabs the current version from the existing `.release-please-manifest`. I should have done this in the first place as it's much cleaner.
=> ci: remove rockspec-info.yml from release-please extra-files

.github/workflows/release-please.yml, examples/hello-haproxy/Dockerfile, release-please-config.json
The release-please workflow's `publish` action will fail because it needs Lua installed (which is done in the `ci` action.)
It might be ideal to have that setup take place independently of `ci` - but here I'm fixing it by adding in `ci` (just as is done in the manual publish workflow.) This is probably a good practice anyways since we don't want to be release code that fails unit tests.
Additionally, the `hello-haproxy` example had a hardcoded rockspec version. This updates it so it can float. Having version numbers in filenames is really the root of a lot of pain here.
=> fix: add missing ci step to release-please workflow

.github/workflows/ci.yml, .github/workflows/manual-publish.yml, .github/workflows/rockspec-info.yml
In the `rockspec-info` workflow, we create a JSON object that contains rockspec versions/filenames that other steps can use. 
The JSON string wasn't outputted correctly, preventing `fromJSON(info)` from returning an object with accessible properties. 
This commit both fixes it and makes it easier to read by utilizing `jq` to create the JSON string. 
I've tested the `manual-publish` and `release-please` workflows on this PR (although can't test the full release flow until this is merged.)
=> fix: rockspec info JSON was generated incorrectly

.github/actions/install-cpp-sdk-redis/action.yml, README.md, examples/hello-haproxy/Dockerfile, examples/hello-nginx/Dockerfile
CPP server had a bug where it was sending a `CPPClient` as its user-agent. This bumps the default version used in Lua's CI and examples.
I've also updated the README minimum versions since this bug affects usage statistics.
=> ci: bump cpp SDK to bring in user-agent fix

launchdarkly-server-sdk-redis.c, launchdarkly-server-sdk.c, scripts/build-docs.sh
It's quite awkward to document ad-hoc tables in Lua created via the C API. Prior to this PR, the `EvaluationDetail` table returned from `*variationDetail` methods didn't have any explanation.
This PR adds documentation of the various fields. Since there's no actual table to document (it's created via C API), the docs are just sort of floating in the file as a comment.
=> docs: add EvaluationDetail table documentation

launchdarkly-server-sdk.c, test.lua
This tiny feature allows users to pass `nil` as the third argument to `clientInit` to request default configuration:
```lua
ld.clientInit("sdk-key", 1000, nil)
```
Before, you had to explicitly pass an empty `{}` table. I think this is more idiomatic/intuitive. I could be wrong.
=> feat: allow nil to be passed for clientInit config

release-please-config.json
Forgot to add `hello-nginx` to release-please config, so it wasn't updated in the latest release PR.
=> chore: add examples/hello-nginx/Dockerfile to release-please config

.github/actions/ci/action.yml, .github/actions/install-cpp-sdk-redis/action.yml, .github/workflows/install-lua-sdk.yml, README.md, examples/hello-haproxy/Dockerfile, examples/hello-nginx/Dockerfile
This version change enables inline contexts for feature events, as well
as anonymous attribute redaction.
=> ci: bump C++ SDK to 3.3.3, C++ Redis to 2.1.3

.github/workflows/ci.yml, examples/hello-debian/Dockerfile, examples/hello-debian/README.md, examples/hello-debian/hello.lua, scripts/get-cpp-sdk-locally.sh
Adds an example that runs in a `debian:bookworm` container.
=> ci: add hello-debian example

.github/actions/ci/action.yml, .github/actions/cpp-versions/action.yml, .github/actions/install-cpp-sdk-redis/action.yml, .github/variables/cpp-sdk-versions.env, .github/workflows/ci.yml, .github/workflows/install-lua-sdk.yml, examples/hello-debian/Dockerfile, examples/hello-haproxy/Dockerfile, examples/hello-nginx/Dockerfile
This consolidates some of the places we need to specify C++ version numbers into a single `cpp-sdk-versions.env` file.
This is a similar approach to Relay Proxy. 
Updating this file will update:
1. CI unit tests
2. Docker example tests 
But it won't update the versions found in README or in the Docker files themselves (as they have default values for the new build arg I've introduced.)
We need to consider the testing strategy going forward. Should we test a min version, and then also a "current" version? And if so, is that current going to float somehow (like using github's releases API to grab the latest), or be pinned to the latest explicitly (via a workflow, or Renovate or something.)
=> ci: use common definition of C++ versions

.github/actions/ci/action.yml, .github/workflows/ci.yml, examples/hello-debian/Dockerfile, examples/hello-debian/README.md, examples/hello-debian/hello.lua, examples/hello-haproxy/README.md, examples/hello-haproxy/service.lua, examples/hello-lua-server/README.md, examples/hello-lua-server/hello.lua, examples/hello-nginx/README.md, examples/hello-nginx/nginx.conf, examples/hello-nginx/shared.lua
Updates all Lua examples to use the verify-hello-app action, and the correct environment variable names. 
This allows the flag key/SDK key to be changed as necessary without any hardcoding.
=> ci: update examples to latest spec

.github/variables/cpp-sdk-versions.env, examples/hello-debian/Dockerfile, examples/hello-haproxy/Dockerfile, examples/hello-nginx/Dockerfile
This pulls in a bugfix which significantly improves the logging experience when given an incorrect SDK key.
=> fix(deps): bump C++ Server to 3.5.2

.github/actions/ci/action.yml, .github/variables/cpp-sdk-versions.env, .github/workflows/install-lua-sdk.yml, README.md, examples/hello-debian/Dockerfile, examples/hello-haproxy/Dockerfile, examples/hello-nginx/Dockerfile
BEGIN_COMMIT_OVERRIDE
fix: Bump launchdarkly-cpp-server to v3.9.0
fix: Bump launchdarkly-cpp-server-redis-source to v2.1.19
END_COMMIT_OVERRIDE
=> fix: Bump SDK and redis source
